version: 2
builds:
  - id: box
    dir: .
    main: ./cmd/gpp/main.go
    binary: gpp-server
    ldflags: -s -w -X main.version={{.Version}}
    flags:
      - -tags=with_quic
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - "386"
      - arm

archives:
  - formats: ["tar.gz"]
    name_template: "gpp-{{ .Os }}-{{ .Arch }}"
    files:
      - none*